### ISSUE TITLE
遇到点问题

### ISSUE THREAD

**Issue by tiam94** [copyliu/bililive_dm#102]
①我的本地网易云喵块失效很久了，一直报这错。
System.DllNotFoundException: Dll was not found.
   at ExtendNetease_DGJModule.PluginMain.InjectDGJ() in F:\Projects\ExtendNetease_DGJModule\ExtendNetease_DGJModule\PluginMain.cs:line 117
   at ExtendNetease_DGJModule.PluginMain.Inited() in F:\Projects\ExtendNetease_DGJModule\ExtendNetease_DGJModule\PluginMain.cs:line 40
   at Bililive_dm.MainWindow.InitPlugins()
②首页不显示弹幕了

**Comment by copyliu** [comment]
插件问题请咨询插件作者
