### ISSUE TITLE
关于连接异常断开后不再重连的问题

### ISSUE THREAD

**Issue by guation** [copyliu/bililive_dm#168]
近期经常性播着播着弹幕连接就会断开，显示获取身份码出错，有时候可以自动重连成功，有时候尝试重连失败后就会弹出失败弹窗，对于全屏游戏主播而言可能要等到长时间无弹幕之后才会发现弹幕姬已经断连，主播身份码并没有发生变更，手动重连可以连上，是否考虑增加无限制自动重连的选项。
```
21:58:40 : 連線被斷開: 開發者資訊System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at BiliDMLib.OpenDanmakuLoader.<HeartbeatLoop>d__34.MoveNext()
21:58:40 : 正在自動重連...
21:58:46 : 獲取身份碼信息出錯
21:58:46 : System.NotSupportedException: 獲取身份碼信息出錯 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bililive_dm.BOpen.<GetRoomInfoByCode>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at Bililive_dm.BOpen.<GetRoomInfoByCode>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bililive_dm.MainWindow.<OPMConnBtn_OnClick>d__101.MoveNext()
```

**Comment by copyliu** [comment]
fixed by https://github.com/copyliu/bililive_dm/commit/22aefd865e55db349bb547548d242e6fdb017e07
