### ISSUE TITLE
无法启动弹幕姬

### ISSUE THREAD

**Issue by benpigchu** [copyliu/bililive_dm#18]
错误报告如下

```
請有空發給 copyliu@gmail.com 謝謝
2017/8/31 19:20:44
System.Windows.Markup.XamlParseException: 对类型“Bililive_dm.MainWindow”的构造函数执行符合指定的绑定约束的调用时引发了异常。 ---> System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
   在 MS.Win32.NativeMethods.IOleCommandTarget.Exec(GUID pguidCmdGroup, Int32 nCmdID, Int32 nCmdexecopt, Object[] pvaIn, Int32 pvaOut)
   在 System.Windows.Controls.WebBrowser.DoNavigate(Uri source, Object& targetFrameName, Object& postData, Object& headers, Boolean ignoreEscaping)
   在 Bililive_dm.MainWindow..ctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   在 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   在 System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   在 System.Windows.Application.DoStartup()
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)-------插件列表--------
```

弹幕姬版本是目前自动更新的最新版本
Windows 版本为 windows 10 insider build 16278

**Comment by copyliu** [comment]
怕是浏览器炸了

**Comment by copyliu** [comment]
2bfd7f3ce405d4f05eb606e20be6e96825810bb5  感觉姑且修复了

**Comment by benpigchu** [comment]
【确实修复了（】

**Comment by KIritoun** [comment]
請有空發給 copyliu@gmail.com 謝謝
2023/11/27 19:48:30
System.IO.InvalidDataException: Invalid MP3 file - no MP3 Frames Detected
   at NAudio.Wave.Mp3FileReader..ctor(Stream inputStream, FrameDecompressorBuilder frameDecompressorBuilder, Boolean ownInputStream)
   at DGJv3.Player.LoadSong(SongItem songItem)
   at DGJv3.Player.NewSongTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)-------插件列表--------
提词版服务端	⑨	CopyLiu	copyliu@gmail.com	启用:True
