### ISSUE TITLE
连接成功后总是不时连接错误反复重连

### ISSUE THREAD

**Issue by rihalvnium76** [copyliu/bililive_dm#93]
出现大量如下日志，且房管助手插件提示无法获取弹幕颜色
```
10:47:57 : 正在連線
10:47:57 : 連線成功
10:47:57 : 連線被斷開: 開發者資訊System.ObjectDisposedException: Cannot access a disposed object.
   at BiliDMLib.utils.<ReadBAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at BiliDMLib.DanmakuLoader.<ReceiveMessageLoop>d__30.MoveNext()
10:47:57 : 正在自動重連...
10:47:58 : 正在連線
10:47:58 : 連線成功
10:47:58 : 連線被斷開: 開發者資訊System.ObjectDisposedException: Cannot access a disposed object.
   at BiliDMLib.utils.<ReadBAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at BiliDMLib.DanmakuLoader.<ReceiveMessageLoop>d__30.MoveNext()
10:47:58 : 正在自動重連...
10:47:58 : 正在連線
10:47:58 : 連線成功
10:49:17 : 弹幕发送 插件已经被允许使用B站账号！
10:51:07 : 連線被斷開: 開發者資訊System.ObjectDisposedException: Cannot access a disposed object.
   at BiliDMLib.utils.<ReadBAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at BiliDMLib.DanmakuLoader.<ReceiveMessageLoop>d__30.MoveNext()
10:51:07 : 正在自動重連...
10:51:07 : 正在連線
10:51:07 : 連線成功
10:51:07 : 連線被斷開: 開發者資訊System.ObjectDisposedException: Cannot access a disposed object.
   at BiliDMLib.utils.<ReadBAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at BiliDMLib.DanmakuLoader.<ReceiveMessageLoop>d__30.MoveNext()
10:51:07 : 正在自動重連...
10:51:08 : 正在連線
10:51:09 : 出錯資訊：System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 120.92.158.137:2243
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BiliDMLib.DanmakuLoader.<ConnectAsync>d__29.MoveNext()
10:51:10 : 正在連線
10:51:10 : 連線成功
10:51:10 : 連線被斷開: 開發者資訊System.ObjectDisposedException: Cannot access a disposed object.
   at BiliDMLib.utils.<ReadBAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at BiliDMLib.DanmakuLoader.<ReceiveMessageLoop>d__30.MoveNext()
10:51:10 : 正在自動重連...
10:51:10 : 正在連線
10:51:10 : 連線成功
10:51:11 : 連線被斷開: 開發者資訊System.ObjectDisposedException: Cannot access a disposed object.
   at BiliDMLib.utils.<ReadBAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at BiliDMLib.DanmakuLoader.<ReceiveMessageLoop>d__30.MoveNext()
10:51:11 : 正在自動重連...
10:51:11 : 正在連線
10:51:11 : 連線成功
```

**Comment by copyliu** [comment]
服務器不穩定
